### ISSUE TITLE
Add example to Readme

### ISSUE THREAD

**Issue by marcofugaro** [ezekg/chrome-github-auto-tab-indent#3]
Do you have an example of this, I had problems understanding what this does.

Sorry if this is not a real issue, feel free to close this.

**Comment by ezekg** [comment]
Of course. I'll add something like this to the readme sometime. With this plugin, looking at source code on GitHub or Bitbucket that uses tabs looks like this,

![image](https://cloud.githubusercontent.com/assets/6979737/12266082/b315000e-b906-11e5-9e92-95c506e07076.png)

but with this plugin, source code looks like this,

![image](https://cloud.githubusercontent.com/assets/6979737/12266091/d283e93c-b906-11e5-88ed-58c4c67a55d7.png)

As you can see, by default, browsers render tabs as 8 (!!!) spaces, but this plugin corrects that by making them render with only 2 spaces (or whatever you specify). Makes reading code on GitHub/Bitbucket a lot more enjoyable, especially when it's in a language like Go, where the standard is to use tabs over spaces.
